#include "geometry.hh"
#include "minimizers.hh"
#include "rastrigin.hh"
#include "shared_result.hh"
#include "solution.hh"

#include "tbb/task_arena.h" // for default_concurrency()
#include "tbb/task_group.h"

#include <chrono>
#include <iostream>
#include <limits>
#include <mutex>
#include <span>
#include <string>
#include <utility>

// This is a simple wrapper to adapt the pfc::rastrigin function to the
// interface expected by dlib.
template <int N>
double
rastrigin_dlib_wrapper(pfc::fixed_vector<N> const& x)
{
  std::span xx = x;
  return pfc::rastrigin(xx);
}

// This is the function that does all the minimization work. We use this to
// provide a scope that ensures that the object 'solutions' has a longer
// lifetime than the task_group 'tasks'.
// It is a blocking function that schedules parallel work, and waits until that
// work is done before returning.
// The template parameter N determines the dimensionality of the rastrigin
// function we will use.
template <int N>
void
do_all_work(pfc::shared_result& solutions, int num_starting_points)
{
  // The task group is what we use to schedule tasks to run.
  oneapi::tbb::task_group tasks;

  // All our starting points will be generated within the region
  // 'starting_point_volume'. They will be generated using random variates
  // generated by 'engine'.
  auto const starting_point_volume = pfc::make_box_in_dim<N>(-10.0, 10.0);
  pfc::protected_engine<std::mt19937> engine;

  for (int i = 0; i != num_starting_points; ++i) {

    pfc::ParallelMinimizer minimizer(
      rastrigin_dlib_wrapper<N>, solutions, starting_point_volume, engine);

    // We have to give a callable with no arguments to tasks.run, so we need
    // a lambda expression that captures all the arguments to be used
    // for the call to minimizer.
    tasks.run([minimizer]() { minimizer(); });
  }
  // Wait for all the tasks in the group to finish.
  tasks.wait();
}

int
main()
{
  // We will start up as many tasks as TBB says we have threads.
  int const num_starting_points = oneapi::tbb::info::default_concurrency();

  // Create shared state for answer.
  // We're done when we have found a minimum with a value < 1.0e-6.
  pfc::shared_result solutions(1.0e-6, num_starting_points);

  auto start = pfc::now_in_milliseconds();
  do_all_work<5>(solutions, num_starting_points);
  auto stop = pfc::now_in_milliseconds();
  auto running_time = stop - start;

  if (solutions.empty()) {
    std::cerr << "No solutions were found in " << running_time
              << " milliseconds\n";
    return 1;
  }

  // We print this count information to standard error so that redirecting
  // standard output to a file does not result in this text also being
  // redirected.
  std::cerr << " A total of " << solutions.num_results()
            << " minimizations were done in " << running_time
            << " milliseconds.\n"
            << solutions.num_results() / running_time
            << " solutions per millisecond\n.";

               solutions.print_report(std::cout);
}
